services:
  trek:
    image: mauriceboe/trek:latest
    container_name: TREK
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    ports:
      - 2341:3000
    volumes:
      - /volume1/docker/trek/data:/app/data:rw
      - /volume1/docker/trek/uploads:/app/uploads:rw
    user: 0:0
    environment:
       NODE_ENV: production
       ENCRYPTION_KEY: dOxZYTTZgXKMHkqLBIQVImayQXAVWdzGBPuFJKggzcgvgPJPXpWzqzKaUOIOGGIr
       TZ: Europe/Bucharest
       ADMIN_EMAIL: hello2ashu@gmail.com
       ADMIN_PASSWORD: Ashgoe@2101
       PORT: 3000
       COOKIE_SECURE: true
    restart: on-failure:5
